### ISSUE TITLE
"Reconciliation" link says "Page Not Found"

### ISSUE THREAD

**Issue by AdarshSahani003** [acdlite/react-fiber-architecture#51]
#### "Reconciliation" link that redirects to "https://facebook.github.io/react/docs/reconciliation.html" says "Page Not Found"

![Screenshot 2024-08-21 123752](https://github.com/user-attachments/assets/e22c6518-5dda-40c7-9bef-0fb95affb938)

**Comment by hcz** [comment]
This repo is a cast in time, so it won't be fixed anytime

The meant links are:
https://legacy.reactjs.org/docs/reconciliation.html
https://legacy.reactjs.org/docs/design-principles.html

**Comment by AdarshSahani003** [comment]
Thanks @hcz for your info
